### ISSUE TITLE
Missing installation notes

### ISSUE THREAD

**Issue by antifob** [nategraf/l2bridge-driver#1]
Hi,

I'd like to know how to install the driver. I'm unable to find installation notes in the repository and the official Docker documentation is unhelpful.

Thanks

**Comment by nategraf** [comment]
When you run the driver it will create a unix socket in `/run/docker/plugins` which Docker will recognize.

You probably want to install it as a service (you can run it without being a service, but Docker will hang whenever it tries to call the driver if it is not running) so I added a script to install it to SysV (Ubuntu/Debian). WIll that work for you?

**Comment by antifob** [comment]
With the added notes and script, it's perfect.

Thanks a lot for sharing your work. :+1:
