### ISSUE TITLE
Overlap not permitted (but project claims it is)

### ISSUE THREAD

**Issue by DerrickRice** [nategraf/l2bridge-driver#4]
I am unable to create two l2bridge networks with overlapping subnets.

I understand that this is a limitation of Docker's default ipam driver. However, if I select a null ipam driver, then I am unable to inform l2bridge of the subnets. It seems that the `--subnets` option for `docker network create` is an open for ipam, which is disallowed if `--ipam-driver=null`, but the information is required for l2bridge.

l2bridge might be able to create a driver option that accepts subnet information, since it cannot be passed via the `ipV4Data` when using the null ipam driver.

**Comment by nategraf** [comment]
So the way I solved this personally was to use a (essentially stubbed out) IPAM driver that allows overlaps. https://github.com/nategraf/static-ipam-driver
